version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgresDB
    restart: always
    env_file:
      - .env
    ports:
      - "3004:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 20s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: FastApiBackend
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  backup:
    build:
      context: ./backupSystem
    container_name: Backupp
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - pgdata:/dbdata:ro
      - ./backupSystem/backups:/app/backups
      - ./backupSystem/logs:/app/logs
      - ./backupSystem/reports:/app/reports
    command: ["sh", "-c", "./search_backup.sh -d /dbdata -b -i -r && crond -f -l 8"]
    user: "0:0"

volumes:
  pgdata:
