services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "3001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  backup:
    build:
      context: ./backupSystem
    container_name: backup
    depends_on:
      - backend
    volumes:
      - pgdata:/dbdata:ro 
      - ./backupSystem/backups:/app/backups
      - ./backupSystem/logs:/app/logs
      - ./backupSystem/reports:/app/reports
      - /home/muteeba/.ssh/id_backup_ed25519:/root/.ssh/id_backup_ed25519:ro
    command: ["sh", "-c", "./search_backup.sh -d /dbdata -i -r && crond -f -l 8"]
    user: "0:0"

volumes:
  pgdata:
