"""initial users and tasks tables

Revision ID: 763b11175bbc
Revises: 22ee0b063576
Create Date: 2025-08-03 19:23:18.814460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763b11175bbc'
down_revision: Union[str, Sequence[str], None] = '22ee0b063576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cnic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cnic')
    # ### end Alembic commands ###
