"""initial users and tasks tables

Revision ID: 804cfe768777
Revises: 763b11175bbc
Create Date: 2025-08-03 19:27:44.570288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804cfe768777'
down_revision: Union[str, Sequence[str], None] = '763b11175bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cnic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cnic', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
